server:
  port: 8087
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        default_schema: users_scheme
